version: '3.7'

services:
  node:
    container_name: node
    build: ./node
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
      - PORT=4000
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - LOCALSTACK_BUCKET=test-awsbucket
    networks:
      - node-localstack
  localstack:
    container_name: localstack
    image: localstack/localstack-full
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_BUCKET=test-awsbucket
    volumes:
      - ./.docker/localstack/tmp/localstack:/tmp/localstack
      - ./.docker/localstack/var/run/docker.sock:/var/run/docker.sock
      - ./.docker/localstack/bin:/docker-entrypoint-initaws.d
    networks:
      - node-localstack

networks:
  node-localstack:
    driver: 'bridge'
